spring:
  application:
    name: user-manager
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  port: 8080
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db:changelog-master:yaml
logging:
  level:
    liquibase: INFO
